apiVersion: v1
kind: Service
metadata:
  name: microservice-2
  labels:
    app: microservice-2
spec:
  selector:
    app: microservice-2
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 3002
  type: ClusterIP