version: '3.8'
services:
  user-service:
    build:
      context: ./user-service
    ports:
      - '3001:3001'
    networks:
      - app-network
    environment:
      - USER_SERVICE_PORT=3001
    volumes:
      - ./user-service:/app
  product-service:
    build:
      context: ./product-service
    ports:
      - '3002:3002'
    networks:
      - app-network
    depends_on:
      - user-service
    environment:
      - PRODUCT_SERVICE_PORT=3002
      - USER_SERVICE_URL=http://user-service:3001
    volumes:
      - ./product-service:/app

networks:
  app-network:
    driver: bridge