apiVersion: v1
kind: Service
metadata:
  name: microservice-1
  labels:
    app: microservice-1
spec:
  selector:
    app: microservice-1
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 3001
  type: ClusterIP